# Config file for Air

# Root directory
root = "./"

# Build path (temporary)
tmp_dir = "tmp"

# Commands to run
[build]
cmd = "go build -o ./tmp/main ./cmd/api/main.go"
bin = "./tmp/main"

# Watch directories
[watch]
include = ["**/*.go"]
exclude = ["tmp", "vendor"]

# Commands to run before building
[[before]]
cmds = ["rm -rf tmp/*"]

# Delay time after the last file change (in milliseconds)
delay = 1000

# Log settings
[log]
log_level = "info"
log_color = true

# Miscellaneous settings
[misc]
kill_signal = "SIGTERM"

# Environment variables
[env]
APP_ENV = "development"
PORT = "9000"